FROM ghcr.io/hdl/sim/osvb

WORKDIR /app

# Install dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        wget build-essential libssl-dev zlib1g-dev \
	    libncurses5-dev libncursesw5-dev libreadline-dev libsqlite3-dev \
		libgdbm-dev libdb5.3-dev libbz2-dev libexpat1-dev liblzma-dev tk-dev \
    && apt-get clean \
    && rm -rf /var/list/apt/lists/*
RUN wget https://www.python.org/ftp/python/3.12.5/Python-3.12.5.tgz
RUN tar -xvf Python-3.12.5.tgz
RUN cd Python-3.12.5 && \
    ./configure --enable-optimizations \
    && make -j$(nproc) \
    && make altinstall \
    && rm -rf Python-3.12.5.tgz Python-3.12.5

# Upgrade pip
RUN python3.12 -m pip install --upgrade pip
RUN pip3.12 install --no-cache-dir requests pyyaml openai google-genai

